nginx:
  extends:
    file: common.yml
    service: nginxproxy
  volumes:
   - ${PROXY_CERT_PATH}:/etc/nginx/ssl
  ports:
   - "80:80"
   - "443:443"

conf:
  image: gentoobb/nginx-proxy-conf
  restart: ${DC_RESTART_POLICY}
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /var/lib/docker/containers:/var/lib/docker/containers
  volumes_from:
   - nginx
