#!/bin/bash
set -xeo pipefail

if [ ! -f /etc/mazaplex.env ]; then
  cat >/etc/mazaplex.env<<END
   export MPLEX_COIN=${MPLEX_COIN:-maza}
   export MPLEX_RPCUSER=${MPLEX_RPCUSER:-coin_rpc}
   export MPLEX_USER=${MPLEX_USER:-coin}
   export MPLEX_RPCPORT=${MPLEX_RPCPOT:-12832}
   export MPLEX_RPCHOST=${MPLEX_RPC_HOST:-localhost}
   export MPLEX_MAZAD_RPCURL=http://${MPLEX_RPCUSER}@${MPLEX_RPCHOST}:${MPLEX_RPCPORT}
   export MPLEX_MAZAD_BLOCKSPATH=${MPLEX_MAZAD_BLOCKS_PATH:-/home/${MPLEX_USER}/.${MPLEX_COIN}/blocks}
   export MPLEX_REDIS=${MPLEX_REDIS:-redis:6379}
   export MPLEX_SSDB=${MPLEX_SSDB:-ssdb:6381}
   export MPLEX_LEVELDB_PATH=${MPLEX_LEVELDB_PATH:-/home/{$MPLEX_USER}/mazaplex_leveldb}
   export MPLEX_APP_URL=${MPLEX_APP_URL:-https://${HOSTNAME}}
   export MPLEX_APP_PORT=${MPLEX_APP_PORT:-6033}
   export MPLEX_API_RATE_LIMITED=${MPLEX_API_RATE_LIMITED:-true}
   export MPLEX_APP_TEMPLATES_PATH=${MPLEX_APP_TEMPLATES_PATH:-templates}
END
fi
. /etc/mazaplex.env


rm /opt/bin/config.json && touch /opt/bin/config.json
echo -e "\"bitcoind_rpc_url\": \"${MPLEX_RPCURL}\"," >> /opt/bin/config.json
echo -e "\"bitcoind_blocks_path\": \"${MPLEX_MAZAD_BLOCKSPATH}\"," >> /opt/bin/config.json     
echo -e "\"redis_host\": \"${MPLEX_REDIS}\"," >> /opt/bin/config.json    
echo -e "\"ssdb_host\": \"${MPLEX_SSDB}\"," >> /opt/bin/config.json     
echo -e "\"leveldb_path\": \"${MPLEX_LEVELDB_PATH}\"," >> /opt/bin/config.json     
echo -e "\"app_url\": \"${MPLEX_APP_URL}\"," >> /opt/bin/config.json     
echo -e "\"app_port\": ${MPLEX_APP_PORT}," >> /opt/bin/config.json     
echo -e "\"app_api_rate_limited\": ${MPLEX_API_RATE_LIMITED}," >> /opt/bin/config.json     
echo -e "\"app_templates_path\": \"${MPLEX_APP_TEMPLATES_PATH}\"">> /opt/bin/config.json     



exec su - coin -c /opt/bin/mazaplex_start.sh

