#!/bin/bash
set -xeo pipefail

MPLEX_COIN=${MPLEX_COIN:-maza}
MPLEX_RPCUSER=${MPLEX_RPCUSER:-coin_rpc}
MPLEX_USER=${MPLEX_USER:-coin}

MPLEX_RPCPORT=${MPLEX_RPCPOT:-12832}
MPLEX_RPCHOST=${MPLEX_RPC_HOST:-localhost}
MPLEX_MAZAD_RPCURL=http://${MPLEX_RPCUSER}@${MPLEX_RPCHOST}:${MPLEX_RPCPORT}
MPLEX_MAZAD_BLOCKSPATH=${MPLEX_MAZAD_BLOCKS_PATH:-/home/${MPLEX_USER}/.${MPLEX_COIN}/blocks}
MPLEX_REDIS=${MPLEX_REDIS:-redis:6379}
MPLEX_SSDB=${MPLEX_SSDB:-ssdb:6381}
MPLEX_LEVELDB_PATH=${MPLEX_LEVELDB_PATH:-/home/{$MPLEX_USER}/mazaplex_leveldb}
MPLEX_APP_URL=${MPLEX_APP_URL:-https://${HOSTNAME}}
MPLEX_APP_PORT=${MPLEX_APP_PORT:-6033}
MPLEX_API_RATE_LIMITED=${MPLEX_API_RATE_LIMITED:-true}
MPLEX_APP_TEMPLATES_PATH=${MPLEX_APP_TEMPLATES_PATH:-templates}

echo -e  \"bitcoind_rpc_url\": \"${MPLEX_RPCURL}\",
        \"bitcoind_blocks_path\": \"${MPLEX_MAZAD_BLOCKSPATH}\",
        \"redis_host": \"redis:6379\",
        \"ssdb_host\": \"ssdb:6381",
        \"leveldb_path\": \"/home/coin/btcplex_leveldb\",
        \"app_url\": \"https:/mazaplex.mazaclub\",
        \"app_port\": 6033,
        \"app_api_rate_limited\": true,
        \"app_templates_path\": \"templates\"



su - coin -c /

