FROM ${NAMESPACE}/bash
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

RUN chmod +x $(find /etc/service -name run) && \
    ln -s /etc/s6_finish_default /etc/service/mazaplex/finish && \
    ln -s /etc/s6_finish_default /etc/service/mazaplex_web/finish && \
    ln -s /etc/service/mazaplex /service && \
    ln -s /etc/service/mazaplex_web /service


ENTRYPOINT ["s6-svscan"]
CMD	   ["/etc/service/"]
